Pizzerito/Pizzerito/Pages/Customer/Cart/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Pizzerito.Pages.Customer.Cart
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ILogger _logger;
        public string Message { get; set; }
        private readonly IUnitOfWork _unitOfWork;

        public IndexModel(IUnitOfWork unitOfWork, ILogger<IndexModel> logger)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
        }

        // view model to add 
        public OrderDetailsCartVM OrderDetailsCartVM { get; set; }
        public void OnGet()
        {
            OrderDetailsCartVM = new OrderDetailsCartVM()
            {
                OrderHeader = new OrderHeader(),
                ListCart = new List<ShoppingCart>()
            };

            //Initialize OrderTotal to 0;
            OrderDetailsCartVM.OrderHeader.OrderTotal = 0;

            //Retrieve shopping cart from db for the logged in user using claims from Dbase

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                //list of the shopping cart
                IEnumerable<ShoppingCart> cart = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value);

                if (cart != null)
                {
                    OrderDetailsCartVM.ListCart = cart.ToList();
                }

                foreach (var cartList in OrderDetailsCartVM.ListCart)
                {
                    cartList.PizzaType = _unitOfWork.PizzaType.GetFirstOrDefault(m => m.Id == cartList.PizzaTypeId);
                    cartList.PizzaType.Category = _unitOfWork.Category.GetFirstOrDefault(c => c.Id == cartList.PizzaType.CategoryId);

                    //order total 

                    OrderDetailsCartVM.OrderHeader.OrderTotal += (cartList.PizzaType.Price * cartList.Count);
                }

            }
            Message = $"Shopping card page visited at {DateTime.UtcNow.ToLongTimeString()}";
            _logger.LogInformation(Message);

        }

        //Custom Handlers for adding, removing,  deleting cart items 
        public IActionResult OnPostPlus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId);
            _unitOfWork.ShoppingCart.IncrementCount(cart, 1);
            _unitOfWork.Save();
            return RedirectToPage("/Customer/Cart/Index");
        }
        public IActionResult OnPostMinus(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId);

            if (cart.Count == 1)
            {
                _unitOfWork.ShoppingCart.Remove(cart);
                _unitOfWork.Save();
                var cnt = _unitOfWork.ShoppingCart
                    .GetAll(u => u.ApplicationUserId == cart.ApplicationUserId)
                    .ToList()
                    .Count;
                HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);

            }
            else
            {
                _unitOfWork.ShoppingCart.DecrementCount(cart, 1);
                _unitOfWork.Save();

            }
            return RedirectToPage("/Customer/Cart/Index");
        }

        public IActionResult OnPostRemove(int cartId)
        {
            var cart = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.Id == cartId);
            _unitOfWork.ShoppingCart.Remove(cart);
            _unitOfWork.Save();

            var cnt = _unitOfWork.ShoppingCart
                    .GetAll(u => u.ApplicationUserId == cart.ApplicationUserId)
                    .ToList()
                    .Count;
            HttpContext.Session.SetInt32(SD.ShoppingCart, cnt);
            return RedirectToPage("/Customer/Cart/Index");
        }
    }
}

Pizzerito/Pizzerito/Pages/Customer/Cart/OrderConfirmation.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Pizzerito.Pages.Customer.Cart
{
    [Authorize]
    public class OrderConfirmationModel : PageModel
    {
        [BindProperty] // from summary post() handler id
        public int orderId { get; set; }
        public void OnGet(int id)
        {
            orderId = id;
        }
    }
}

Pizzerito/Pizzerito/Pages/Customer/Cart/Summary.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Utility;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Pizzerito.Pages.Customer.Cart
{
    [Authorize]
    public class SummaryModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public SummaryModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // view model to add 
        [BindProperty] // bind property to make it available to the OnPost() handler
        public OrderDetailsCartVM DetailCart { get; set; }
        public IActionResult OnGet()
        {
            DetailCart = new OrderDetailsCartVM()
            {
                OrderHeader = new OrderHeader()
            };

            //Initialize OrderTotal to 0;
            DetailCart.OrderHeader.OrderTotal = 0;

            //Retrieve shopping cart from db for the logged in user using claims 

            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            //retrieve shopping cart
            IEnumerable<ShoppingCart> cart = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value);

            if (cart != null)
            {
                DetailCart.ListCart = cart.ToList();
            }

            foreach (var cartList in DetailCart.ListCart)
            {
                cartList.PizzaType = _unitOfWork.PizzaType.GetFirstOrDefault(m => m.Id == cartList.PizzaTypeId);
                cartList.PizzaType.Category = _unitOfWork.Category.GetFirstOrDefault(c => c.Id == cartList.PizzaType.CategoryId);

                //order total 

                DetailCart.OrderHeader.OrderTotal += (cartList.PizzaType.Price * cartList.Count);
            }

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(c => c.Id == claim.Value);
            DetailCart.OrderHeader.PickupName = applicationUser.FullName;
            DetailCart.OrderHeader.PickUpTime = DateTime.Now;
            DetailCart.OrderHeader.PhoneNumber = applicationUser.PhoneNumber;
            return Page();
        }

        // stripe payment handler 
        public IActionResult OnPost(string stripeToken)
        {
            //create OrderHeader and Order Details and add inside the database
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            // Retrieve all the items from the shopping cart 
            DetailCart.ListCart = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == claim.Value).ToList();

            //Update OrderHeader and change the PaymentStatus for the order status and payment and add Date/Time
            DetailCart.OrderHeader.PaymentStatus = SD.PaymentStatusPending;
            DetailCart.OrderHeader.OrderDate = DateTime.Now;
            DetailCart.OrderHeader.UserId = claim.Value;
            DetailCart.OrderHeader.Status = SD.PaymentStatusPending;
            DetailCart.OrderHeader.PickUpTime = Convert.ToDateTime(DetailCart
                                                                .OrderHeader
                                                                .PickUpDate
                                                                .ToShortDateString() + " " + DetailCart
                                                                .OrderHeader
                                                                .PickUpTime
                                                                .ToShortTimeString()
                                                                );
            DetailCart.OrderHeader.PhoneNumber = DetailCart.OrderHeader.PhoneNumber.Replace(" ", "")
                                        .Replace("(", "")
                                        .Replace(")", "")
                                        .Replace("-", "");

            List<OrderDetails> orderDetailslist = new List<OrderDetails>();
            _unitOfWork.OrderHeader.Add(DetailCart.OrderHeader);
            _unitOfWork.Save();

            //Loop through OrderDetails
            foreach (var item in DetailCart.ListCart)
            {
                item.PizzaType = _unitOfWork.PizzaType.GetFirstOrDefault(m => m.Id == item.PizzaTypeId);
                OrderDetails orderDetails = new OrderDetails
                {
                    PizzaTypeID = item.PizzaTypeId,
                    OrderId = DetailCart.OrderHeader.Id,
                    Description = item.PizzaType.Description,
                    Name = item.PizzaType.Name,
                    Price = item.PizzaType.Price,
                    Count = item.Count
                };
                // Modify the Order Total 

                DetailCart.OrderHeader.OrderTotal += (orderDetails.Count * orderDetails.Price);
                // add to orderDetails database 
                _unitOfWork.OrderDetails.Add(orderDetails);
            }
            //added string conversion for formating price to $0.00 
            DetailCart.OrderHeader.OrderTotal = DetailCart.OrderHeader.OrderTotal;
            // remove from cart from database using RemoveRange ref (Irepository, Repository)
            _unitOfWork.ShoppingCart.RemoveRange(DetailCart.ListCart);

            // End Session
            HttpContext.Session.SetInt32(SD.ShoppingCart, 0);
            _unitOfWork.Save();

            if (stripeToken != null)
            {
                // Charge Stripe using creditcard (Stripe Logic)
                var options = new ChargeCreateOptions
                {
                    //add amount in cents for stripe 
                    Amount = Convert.ToInt32(DetailCart.OrderHeader.OrderTotal * 100),
                    Currency = "usd",
                    Source = stripeToken, // from  IActionResult OnPost(string stripeToken) argument
                    Description = "Order ID : " + DetailCart.OrderHeader.Id, // from cart Orderheader.Id 
                };
                var service = new ChargeService();
                Charge charge = service.Create(options);

                // Log transaction ID from stripe to database 

                DetailCart.OrderHeader.TransactionId = charge.Id;

                if (charge.Status.ToLower() == "succeeded")
                {
                    // if successful send email 
                    DetailCart.OrderHeader.PaymentStatus = SD.PaymentStatusApproved;
                    DetailCart.OrderHeader.Status = SD.StatusSubmitted;
                }
                else // not successful
                {
                    DetailCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
                }

            }
            else // if stripeToken == null
            {
                DetailCart.OrderHeader.PaymentStatus = SD.PaymentStatusRejected;
            }
            _unitOfWork.Save();
            // when successful transaction, redirect to OrderConfirmation page 
            return RedirectToPage("/Customer/Cart/OrderConfirmation", new { id = DetailCart.OrderHeader.Id });
        }

    }
}

Pizzerito/Pizzerito/Pages/Customer/Home/Details.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Pizzerito.Pages.Customer.Home
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public DetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public ShoppingCart ShopingCartObj { get; set; }

        public IEnumerable<PizzaType> PizzaTypeList { get; set; }
        public IEnumerable<Toppings> ToppingsList { get; set; }
        public void OnGet(int id)
        {
            ShopingCartObj = new ShoppingCart()
            {

                PizzaType = _unitOfWork.PizzaType.GetFirstOrDefault(includeProperties: "Category,ToppingType,PizzaCrustType,PizzaCrustFlavor,PizzaSize", filter: c => c.Id == id),
                PizzaTypeId = id
            };

            PizzaTypeList = _unitOfWork.PizzaType
               .GetAll(null, q => q.OrderBy(c => c.PizzaSize.Size), "Category,ToppingType,PizzaCrustType,PizzaCrustFlavor,PizzaSize");
            ToppingsList = _unitOfWork.Toppings.GetAll(null, q => q.OrderBy(c => c.Id), null);
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
                // Retrieve the user id of the logged in user 
                var claimsIdentity = (ClaimsIdentity)this.User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

                ShopingCartObj.ApplicationUserId = claim.Value;
                //access the database for shopping cart 

                ShoppingCart cartFromDb = _unitOfWork.ShoppingCart.GetFirstOrDefault(c => c.ApplicationUserId == ShopingCartObj.ApplicationUserId &&
                                          c.PizzaTypeId == ShopingCartObj.PizzaTypeId);

                if (cartFromDb == null) // add new item to cart 
                {
                    _unitOfWork.ShoppingCart.Add(ShopingCartObj);

                }
                else // if object exists increment count of object 
                {

                    _unitOfWork.ShoppingCart.IncrementCount(cartFromDb, ShopingCartObj.Count);
                }
                _unitOfWork.Save();
                //increase the session 
                var count = _unitOfWork.ShoppingCart.GetAll(c => c.ApplicationUserId == ShopingCartObj.ApplicationUserId).ToList().Count;
                HttpContext.Session.SetInt32(SD.ShoppingCart, count);
                return RedirectToPage("Index");
            }
            else
            {
                ShopingCartObj.PizzaType = _unitOfWork.PizzaType.GetFirstOrDefault(includeProperties: "Category,ToppingType,PizzaCrustType,PizzaCrustFlavor,PizzaSize", filter: c => c.Id == ShopingCartObj.PizzaTypeId);
                return Page();
            }
        }
    }
}

Pizzerito/Pizzerito/Pages/Customer/Home/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Utility;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Pizzerito.Pages.Customer.Home
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IEnumerable<PizzaType> PizzaTypeList { get; set; }
        public IEnumerable<Category> CategoryList { get; set; }
        public IEnumerable<ToppingType> ToppingTypeList { get; set; }
        public void OnGet()
        {
            // Retrieve the user id of the logged in user 
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                int ShoppingCartCount = _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).ToList().Count;
                // assign to HttpContext 
                HttpContext.Session.SetInt32(SD.ShoppingCart, ShoppingCartCount);
            }

            PizzaTypeList = _unitOfWork.PizzaType
                .GetAll(null, q => q.OrderBy(c => c.PizzaSize.Size), "Category,ToppingType,PizzaCrustType,PizzaCrustFlavor,PizzaSize");
            CategoryList = _unitOfWork.Category.GetAll(null, q => q.OrderBy(c => c.DisplayOrder), null);
            ToppingTypeList = _unitOfWork.ToppingType.GetAll(null, q => q.OrderBy(c => c.Id), null);
        }
    }
}

Pizzerito/Pizzerito/Pages/Customer/Cart/Index.cshtml
@page
@model Pizzerito.Pages.Customer.Cart.IndexModel
@{
    ViewData["Title"] = "Shopping Cart";
}
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<form method="post">

    <br />
    @if (Model.OrderDetailsCartVM.ListCart.Count > 0)
    {
        <input asp-for="@Model.OrderDetailsCartVM.ListCart[0].ApplicationUserId" hidden />
        <div class="backgroundWhiteBorder">
            <div class="container">
                <div class="card">
                    <div class="card-header bg-light text-success ml-0 row container">
                        <div class="col-6 h4 text-nowrap">
                            <i class="fa fa-shopping-cart"></i> &nbsp;
                            @Localizer["Shopping Cart"]
                        </div>
                        <div class="col-6 text-right">
                            <a asp-page="../Home/Index" class="btn popup-button-primary text-center btn-product red text-decoration-none">@Localizer["Continue Shopping"]</a>
                        </div>
                    </div>
                    <div class="card-body">
                        @foreach (var item in Model.OrderDetailsCartVM.ListCart)
                        {
                            <div class="row">
                                <div class="d-none d-lg-block col-lg-2 text-center py-2">
                                    <img src="@item.PizzaType.Image" class="rounded card-product" style="height:100px!important; border: none!important;" />
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-left">
                                    <h4 class="text-capitalize">@SharedLocalizer[@item.PizzaType.Name] @SharedLocalizer[@item.PizzaType.Category.Name]</h4>
                                </div>
                                <div class="col-12 text-sm-center col-lg-5 text-lg-right row">
                                    <div class="col-4 text-md-right" style="padding-top:5px;">
                                        <h6><strong>@(item.PizzaType.Price.ToString("C", CultureInfo.CurrentCulture))<span class="text-muted">x</span> @item.Count </strong></h6>
                                    </div>
                                    <div class="col-6 col-sm-4 col-lg-6">
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn popup-button-primary" asp-page-handler="plus" asp-route-cartid="@item.Id">
                                                <i class="fas fa-plus"></i>
                                            </button>
                                        </div>
                                        <div class="float-right mx-1">
                                            <button type="submit" class="btn popup-button-danger" asp-page-handler="minus" asp-route-cartid="@item.Id">
                                                <i class="fas fa-minus"></i>
                                            </button>
                                        </div>
                                    </div>
                                    <div class="col-2 col-sm-4 col-lg-2 text-right">
                                        <button type="submit" class="btn btn-outline-danger" asp-page-handler="remove" asp-route-cartid="@item.Id">
                                            <i class="fas fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                            <hr />
                        }


                        <div class="row">
                            <div class="col-12 col-md-5">

                            </div>
                            <div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
                                <ul class="list-group">
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <span class="text-info">@Localizer["Total (USD)"]</span>
                                        <strong class="text-info">$<span id="txtOrderTotal">@Model.OrderDetailsCartVM.OrderHeader.OrderTotal.ToString("#,##0.00")</span></strong>
                                    </li>
                                </ul>
                            </div>
                        </div>


                    </div>
                    <div class="card-footer">
                        <div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
                            <a asp-page="Summary" class="popup-button form-control btn-product green text-decoration-none text-center" style="line-height: 1;">@Localizer["Summary"]</a>
</div>
                    </div>
                </div>
            </div>
        </div>

    }
    else
    {
<div>
    @Localizer["Please add items to shopping cart."]
</div>
    }

</form>

Pizzerito/Pizzerito/Pages/Customer/Cart/OrderConfirmation.cshtml
@page
@model Pizzerito.Pages.Customer.Cart.OrderConfirmationModel
@{
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<div class="container row">
    <div class="col-12 text-center">
        <h1 class="text-primary text-center">@Localizer["Order Placed Successfully!"]</h1>
        @Localizer["Your Order Number is"]: @Model.orderId <br /><br />
        <img src="~/images/pizza.gif" style="width:65%" />
    </div>
    <div class="col-12 text-center" style="color:maroon;">
        <br />
        @Localizer["Your order has been placed successfully!"] <br />
        @Localizer["Please make sure to arrive on time to pick it up!"]
    </div>
</div>