Pizzerito/Pizzerito/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Models.ViewModels;
using Pizzerito.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;

namespace Pizzerito.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class OrderController : Controller
    {
        private readonly ILogger _logger;
        private readonly IUnitOfWork _unitOfWork;

        public OrderController(ILogger<OrderController> logger, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
        }
        //Updated to get data from OrderList page for Cancelled, Completed, or Inprocessed orders 
        [HttpGet]
        [Authorize]
        public IActionResult Get(string status = null, DateTime startDate = new DateTime(), DateTime endDate = new DateTime())
        {
            _logger.LogInformation($"Enter /api/order");
            List<OrderDetailsVM> orderListVM = new List<OrderDetailsVM>();

            IEnumerable<OrderHeader> OrderHeaderList;

            if (User.IsInRole(SD.CustomerRole))
            {
                // retrieve all order for the logged in customer from database
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                // get info from single customer and display ApplicationUser properties 
                OrderHeaderList = _unitOfWork.OrderHeader.GetAll(u => u.UserId == claim.Value, null, "ApplicationUser");
            }
            else
            {
                //If not customer retrieve all the orders 
                OrderHeaderList = _unitOfWork.OrderHeader.GetAll(null, null, "ApplicationUser");
            }

            //Added to get data from OrderList page for Cancelled, Completed, or Inprocessed orders 
            if (status == "cancelled")
            {
                _logger.LogInformation($"Find all cancelled, refund or rejected orders");
                OrderHeaderList = OrderHeaderList.Where(o => o.Status == SD.StatusCancelled
                                                        || o.Status == SD.StatusRefunded
                                                        || o.Status == SD.PaymentStatusRejected);
            }
            else
            {
                if (status == "completed")
                {
                    _logger.LogInformation($"Find all completed orders");
                    OrderHeaderList = OrderHeaderList.Where(o => o.Status == SD.StatusCompleted);
                }
                else
                {
                    _logger.LogInformation($"Find all ready, in progress submitted or payment pending orders");
                    OrderHeaderList = OrderHeaderList.Where(o => o.Status == SD.StatusReady
                                                                || o.Status == SD.StatusInProcess
                                                                || o.Status == SD.StatusSubmitted
                                                                || o.Status == SD.PaymentStatusPending);
                }
            }
            _logger.LogInformation($"Fiter orders by date: start-{startDate}, end-{endDate}");
            OrderHeaderList = OrderHeaderList.Where(o => o.OrderDate >= startDate && o.OrderDate <= endDate);
            foreach (OrderHeader item in OrderHeaderList)
            {
                OrderDetailsVM individual = new OrderDetailsVM
                {
                    // assign order header 
                    OrderHeader = item,
                    // retrieve from DataBase
                    OrderDetails = _unitOfWork.OrderDetails.GetAll(o => o.OrderId == item.Id).ToList()
                };
                // Add to orderListVM
                orderListVM.Add(individual);
            }

            _logger.LogInformation($"Return all orders, returning HTTP 200 - OK");
            return Json(new { data = orderListVM });
        }
    }
}

Pizzerito/Pizzerito/Pages/Admin/Order/ManageOrder.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Models.ViewModels;
using Pizzerito.Utility;
using Stripe;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Pizzerito.Pages.Admin.Order
{
    [Authorize(Roles = SD.ManagerRole)]
    public class ManageOrderModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public ManageOrderModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public List<OrderDetailsVM> orderDetailsVM { get; set; }


        public void OnGet()
        {
            orderDetailsVM = new List<OrderDetailsVM>();


            List<OrderHeader> OrderHeaderList = _unitOfWork.OrderHeader.GetAll(o => o.Status == SD.StatusSubmitted
                                                                                 || o.Status == SD.StatusInProcess)
                                                                                     .OrderByDescending(u => u.PickUpTime)
                                                                                     .ToList();

            foreach (OrderHeader item in OrderHeaderList)
            {
                OrderDetailsVM individual = new OrderDetailsVM
                {
                    // assign order header 
                    OrderHeader = item,
                    // retrieve from DataBase
                    OrderDetails = _unitOfWork.OrderDetails.GetAll(o => o.OrderId == item.Id).ToList()
                };
                // Add to orderListVM
                orderDetailsVM.Add(individual);
            }

        }


        public IActionResult OnPostOrderPrepare(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);
            orderHeader.Status = SD.StatusInProcess;
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }

        public IActionResult OnPostOrderReady(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);
            orderHeader.Status = SD.StatusReady;
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }

        public IActionResult OnPostOrderCancel(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);
            orderHeader.Status = SD.StatusCancelled;
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }

        public IActionResult OnPostOrderRefund(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);

            // refund the amount 
            var options = new RefundCreateOptions
            {
                Amount = Convert.ToInt32(orderHeader.OrderTotal * 100),
                Reason = RefundReasons.RequestedByCustomer,
                Charge = orderHeader.TransactionId
            };
            var service = new RefundService();
            Refund refund = service.Create(options);

            //change the status to refund
            orderHeader.Status = SD.StatusRefunded;
            _unitOfWork.Save();
            return RedirectToPage("ManageOrder");
        }

    }
}

Pizzerito/Pizzerito/Pages/Admin/Order/OrderDetails.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Pizzerito.DataAccess.Data.Repository.IRepository;
using Pizzerito.Models;
using Pizzerito.Models.ViewModels;
using Pizzerito.Utility;
using Stripe;
using System;
using System.Linq;

namespace Pizzerito.Pages.Admin.Order
{
    [Authorize]
    public class OrderDetailsModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;

        public OrderDetailsModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [BindProperty]
        public OrderDetailsVM OrderDetailsVM { get; set; }
        public void OnGet(int id)
        {
            OrderDetailsVM = new OrderDetailsVM()
            {
                OrderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(m => m.Id == id),
                OrderDetails = _unitOfWork.OrderDetails.GetAll(m => m.OrderId == id).ToList()
            };

            OrderDetailsVM.OrderHeader.ApplicationUser = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == OrderDetailsVM.OrderHeader.UserId);
        }

        public IActionResult OnPostOrderConfirm(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);
            orderHeader.Status = SD.StatusCompleted;
            _unitOfWork.Save();
            return RedirectToPage("OrderList");
        }

        public IActionResult OnPostOrderCancel(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);
            orderHeader.Status = SD.StatusCancelled;
            _unitOfWork.Save();
            return RedirectToPage("OrderList");
        }

        public IActionResult OnPostOrderRefund(int orderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.GetFirstOrDefault(o => o.Id == orderId);

            // refund the amount 
            var options = new RefundCreateOptions
            {
                Amount = Convert.ToInt32(orderHeader.OrderTotal * 100),
                Reason = RefundReasons.RequestedByCustomer,
                Charge = orderHeader.TransactionId
            };
            var service = new RefundService();
            Refund refund = service.Create(options);

            //change the status to refund
            orderHeader.Status = SD.StatusRefunded;
            _unitOfWork.Save();
            return RedirectToPage("OrderList");
        }
    }
}

Pizzerito/Pizzerito/Pages/Admin/Order/OrderList.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Pizzerito.Pages.Admin.Order
{
    [Authorize]
    public class OrderListModel : PageModel
    {

        public IActionResult OnGet()
        {
            return Page();
        }
    }
}

Pizzerito/Pizzerito/Pages/Admin/Order/ManageOrder.cshtml
@page
@model Pizzerito.Pages.Admin.Order.ManageOrderModel
@using Pizzerito.Utility
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


    <h1 class="text-primary py-3">@Localizer["Manage Order's"]</h1>

<form method="post">
    @if (Model.orderDetailsVM.Count > 0)
    {
        <div class="container row bg-white p-2 border mb-3 rounded">
            @foreach (var item in Model.orderDetailsVM)
            {
                <div class="col-12 card-product pb-3 pt-3 mt-4 border rounded">
                    <div class="bg-white  ">
                        <div class="row" id="demo">
                            <div class="col-12 col-sm-4">
                                @Localizer["Order Number"] : @item.OrderHeader.Id
                                <ul class="text-info">
                                    @foreach (var details in item.OrderDetails)
                                    {
                                        <li id="orderName" class="d-flex text-capitalize text-nowrap">@details.Name  <span class="text-lowercase ml-1"> x @details.Count</span></li>
                                    }
                                </ul>
                            </div>
                            <div class="col-12 col-sm-4 pb-2">
                                <div class="input-group pb-2">
                                    <div class="input-group-append">
                                        <span class="input-group-text">@Localizer["Pickup Time:"]</span>
                                    </div>
                                    <p hidden class="exp1"> @item.OrderHeader.PickUpTime </p>
                                    <input type="text" class=" border rounded form-control" readonly value="@item.OrderHeader.PickUpTime" />
                                </div>
                                @{
                                    var comments = item.OrderHeader.Comments;
                                    if (comments == null || comments.Trim().Length == 0)
                                    {

                                        item.OrderHeader.Comments = @Localizer["No Instructions."].Value;
                                        <textarea hidden asp-for="@item.OrderHeader.Comments" readonly class="rounded border form-control" style="width:100%;height:75px;"></textarea>

                                    }
                                    else
                                    {
                                        <textarea asp-for="@item.OrderHeader.Comments" readonly class="rounded border form-control" style="width:100%;height:75px;"></textarea>

                                    }
                                }
                            </div>
                            <div class="col-12 col-sm-3 offset-sm-1 d-flex  align-content-center">
                                <div class="col-12">

                                    @*added timer to track countdown to order in progress*@
                                    <div class="progress">
                                        <div class="progressTimer progress-bar progress-bar-striped progress-bar-animated"></div>
                                    </div>
                                    <div class="col-12 timer text-center text-wrap font-weight-light mb-4" style="font-size:14px;"></div>
                                    @*end update*@

                                    @if (item.OrderHeader.Status.Equals(Pizzerito.Utility.SD.StatusSubmitted))
                                    {
                                <button type="submit" class="btn btn-primary form-control mb-2" asp-page-handler="OrderPrepare" asp-route-OrderId="@item.OrderHeader.Id">
                                    <i class="fas fa-check"></i> &nbsp; @Localizer["Start Cooking"]
                                </button>
                                    }
                                    else
                                    {
                                        if (item.OrderHeader.Status.Equals(Pizzerito.Utility.SD.StatusInProcess))
                                        {
                                <button type="submit" class="btn btn-success form-control mb-3" asp-page-handler="OrderReady" asp-route-OrderId="@item.OrderHeader.Id">
                                    <i class="fas fa-flag-checkered"></i> &nbsp; @Localizer["Order Ready"]
                                </button>
                                        }
                                    }
                                <button type="submit" class="btn btn-warning form-control mb-3" asp-page-handler="OrderCancel" asp-route-OrderId="@item.OrderHeader.Id">
                                    <i class="fas fa-times"></i> &nbsp; @Localizer["Cancel Order"]
                                </button>
                                <button type="submit" class="btn btn-danger form-control mb-3" asp-page-handler="OrderRefund" asp-route-OrderId="@item.OrderHeader.Id">
                                    <i class="fas fa-times"></i> &nbsp; @Localizer["Refund Order"]
                                </button>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            }

        </div>
    }
    else
    {
        <div class="card">
            <div class="card-body text-center bg-light"><h2>@Localizer["No Orders yet.."]</h2> </div>
        </div>
    }

</form>

@*specific style to this page only*@
@*<style>

        li{
            text-transform: capitalize;
        }

    </style>*@

@section Scripts{
    <script src="~/js/countTimer.js"></script>

}

Pizzerito/Pizzerito/Pages/Admin/Order/OrderDetails.cshtml
@page
@model Pizzerito.Pages.Admin.Order.OrderDetailsModel
@using Pizzerito.Utility
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<form method="post">
    <div class="border ml-1 backgroundWhite mt-4">
        <div class="row pb-1">
            <div class="col-12 col-md-6 ">
                <p class="h2  text-primary">@Localizer["Order Details"]</p>
</div>
            <div class="col-12 col-md-4 offset-md-2">
                <a asp-page="/Admin/Order/OrderList" class="btn btn-success form-control">@Localizer["Back to Orders"] </a>
            </div>
        </div>
        <hr />

        <div class="row pt-2">

            <div class="col-lg-7 col-12" style="border-right:1px solid #bbb9b9">
                <input type="hidden" asp-for="OrderDetailsVM.OrderHeader.Id" />
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label>@Localizer["Name"]</label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailsVM.OrderHeader.PickupName" disabled class="form-control text-capitalize" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label><label asp-for="OrderDetailsVM.OrderHeader.ApplicationUser.Email">@Localizer["Email"]</label></label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailsVM.OrderHeader.ApplicationUser.Email" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label>@Localizer["Phone number"]</label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input id="ContactPhone" asp-for="OrderDetailsVM.OrderHeader.ApplicationUser.PhoneNumber" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsVM.OrderHeader.OrderTotal">@Localizer["Order total"]</label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input asp-for="OrderDetailsVM.OrderHeader.OrderTotal" asp-format="{0:C}" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3 col-12 text-primary">
                        <label asp-for="OrderDetailsVM.OrderHeader.PickUpTime">@Localizer["Pick up time"]</label>
                    </div>
                    <div class="col-md-9 col-12">
                        <input value="@Model.OrderDetailsVM.OrderHeader.PickUpTime.ToShortDateString() @Model.OrderDetailsVM.OrderHeader.PickUpTime.ToShortTimeString()" disabled class="form-control" />
                    </div>
                </div>

                @if (Model.OrderDetailsVM.OrderHeader.Comments != null)
                {
                    <div class="form-group row">
                        <div class="col-md-3 col-12 text-primary">
                            <label asp-for="OrderDetailsVM.OrderHeader.Comments">@Localizer["Comments"]</label>
                        </div>
                        <div class="col-md-9 col-12">
                            <input asp-for="OrderDetailsVM.OrderHeader.Comments" disabled class="form-control" />
                        </div>
                    </div>
                }
            </div>

            <div class="col-lg-5 col-12">
                <h4 class="d-flex justify-content-between align-content-center mb-3">
                    <span class="text-muted">@Localizer["Order ID:"] </span>
                    <span class="badge badge-secondary badge-pill dot-red text-white" style="line-height: 1.5;">@Model.OrderDetailsVM.OrderHeader.Id</span>
                </h4>
                <ul class="list-group mb-3">

                    @foreach (var details in Model.OrderDetailsVM.OrderDetails)
                    {
                        <li class="list-group-item d-flex justify-content-between">
                            <div>
                                <h6 class="my-0 text-capitalize">@SharedLocalizer[@details.Name]</h6>
                                <small class="text-muted">@Localizer["Quantity :"] @details.Count</small>
                            </div>
                            <span class="text-muted">$@(details.Price * details.Count)</span>
                        </li>
                    }
                    <li class="list-group-item d-flex justify-content-between bg-light">
                        <span class="text-info">@Localizer["Total (USD)"]</span>
                        <strong class="text-info">$@Model.OrderDetailsVM.OrderHeader.OrderTotal.ToString("#,##0.00")</strong>
                    </li>
                </ul>
                @if (Model.OrderDetailsVM.OrderHeader.Status.Equals(SD.StatusReady) && (User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole)))
                {
                    <button type="submit" class="btn btn-success form-control" asp-page-handler="OrderConfirm" asp-route-OrderId="@Model.OrderDetailsVM.OrderHeader.Id"><i class="far fa-thumbs-up"></i>@Localizer["Confirm Pickup"]</button>
                }
                else
                {
                    <button type="submit" disabled class="btn btn-info form-control">@SharedLocalizer[@Model.OrderDetailsVM.OrderHeader.Status] </button>
                }

                @if ((User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole))
              && (Model.OrderDetailsVM.OrderHeader.Status.Equals(SD.StatusSubmitted)
              || Model.OrderDetailsVM.OrderHeader.Status.Equals(SD.StatusReady)
              || Model.OrderDetailsVM.OrderHeader.Status.Equals(SD.StatusInProcess)))
                {
                    <div class="row pt-3">
                        <div class="col-6">
                            <button type="submit" class="btn btn-warning form-control" asp-page-handler="OrderCancel" asp-route-OrderId="@Model.OrderDetailsVM.OrderHeader.Id"><i class="fas fa-times"></i> @Localizer["Cancel Order"]</button>
                        </div>
                        <div class="col-6">
                            <button type="submit" class="btn btn-danger form-control" asp-page-handler="OrderRefund" asp-route-OrderId="@Model.OrderDetailsVM.OrderHeader.Id"><i class="fas fa-times"></i> @Localizer["Refund Order"]</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <script>
        $(function () {

            $("#ContactPhone").mask("(999) 999-9999");
        });

    </script>
}

Pizzerito/Pizzerito/Pages/Admin/Order/OrderList.cshtml
@page
@model Pizzerito.Pages.Admin.Order.OrderListModel
@using Pizzerito.Utility
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    var status = HttpContext.Request.Query["status"];
    var cancelled = "text-primary";
    var completed = "text-primary";
    var inProcess = "text-primary";

    if (status == "cancelled")
    {
        cancelled = "active text-white";
    }
    else
    {
        if (status == "completed")
        {
            completed = "active text-white";
        }
        else
        {
            inProcess = "active text-white";
        }
    }
}

@if (User.IsInRole(SD.CustomerRole) || User.IsInRole(SD.ManagerRole) || User.IsInRole(SD.FrontDeskRole) || User.IsInRole(SD.PizzaMakerRole))
{
    <div class="border backgroundWhite container">
        <div class="d-flex justify-content-around mb-3 flex-wrap flex-md-nowrap">
            <div class="p-2">
                <h2 class="text-primary font-weight-light">@Localizer["Order's List"]</h2>
            </div>
            <div class="input-group rounded-0 align-items-center">
                <label class="pr-2" for="datapicker">@Localizer["Date range"]</label>
                <input type="text" autocomplete="off" class="form-control" value="" id="datepicker">
            </div>
            <div class="p-2">
                <ul class="list-group list-group-horizontal-sm">
                    <li class="list-group-item @cancelled"><a class="link-dark" asp-page="OrderList" asp-route-status="cancelled">@Localizer["Cancelled"] </a></li>
                    <li class="list-group-item @completed"> <a class="link-dark" asp-page="OrderList" asp-route-status="completed"> @Localizer["Completed"]</a> </li>              
                    <li class="list-group-item @inProcess"><a class="link-dark" asp-page="OrderList" asp-route-status="inProcess"> @Localizer["In process"] </a></li>
                </ul>
            </div>
        </div>
        <br />
        <table id="DT-load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>@Localizer["Order ID"]</th>
                    <th>@Localizer["Name"]</th>
                    <th>@Localizer["Email"]</th>
                    <th>@Localizer["Date Ordered"]</th>
                    <th>@Localizer["Order Total"]</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
}
else
{
    <header>
        <h1 class="text-danger">@Localizer["Access Denied"]</h1>
        <p class="text-danger">@Localizer["You do not have access to this resource."]</p>
    </header>
}

<style>

    tr td:nth-child(2) {
        text-transform: capitalize;
    }
</style>

@section Scripts{
    <script src="~/js/orderList.js"></script>

}